In [8]:
import pandas as pd
import os

In [9]:
dataset_id = 'amangarg08/apple-retail-sales-dataset'
target_dir = '../data/raw'

## Script to download and Unzip Data from Kaggle

In [ ]:

from kaggle.api.kaggle_api_extended import KaggleApi

In [ ]:
api = KaggleApi()
api.authenticate()

In [ ]:
os.makedirs(target_dir, exist_ok=True)

In [ ]:
if os.listdir(target_dir):
    print(f"Data already exists in {target_dir}. Skipping download.")
else:
    print(f"Downloading dataset {dataset_id} to {target_dir}...")
    api.dataset_download_files(dataset_id, path=target_dir, unzip=True)
    print(f"Dataset {dataset_id} downloaded and extracted to {target_dir}.")

Files to use: **sales.csv**, **products.csv**, **stores.csv**, **warranty.csv**

In [10]:
sales_df = pd.read_csv(os.path.join(target_dir, 'sales.csv'))

In [11]:
sales_df.head()

     sale_id   sale_date store_id product_id  quantity
0    YG-8782  16-06-2023    ST-10       P-38        10
1  QX-999001  13-04-2022    ST-63       P-48        10
2   JG-46890  05-07-2021    ST-26       P-79         5
3    XJ-1731  20-07-2022    ST-15       P-24         9
4   FG-95080  18-03-2022    ST-35       P-69         7

In [ ]:
sales_df.shape

In [ ]:
sales_df.info()

In [ ]:
sales_df.describe(include="all")

In [ ]:
max(sales_df['quantity'])

In [ ]:
print(f"Number of unique sale IDs: {sales_df['sale_id'].nunique()}")
print(f"Number of unique store IDs: {sales_df['store_id'].nunique()}")
print(f"Number of unique product IDs: {sales_df['product_id'].nunique()}")

In [ ]:
# After capitalizing the IDs, we can check the number of unique IDs again to see if there are any duplicates due to case sensitivity.
print(f"Number of unique sale IDs: {sales_df['sale_id'].str.upper().nunique()}")
print(f"Number of unique store IDs: {sales_df['store_id'].str.upper().nunique()}")
print(f"Number of unique product IDs: {sales_df['product_id'].str.upper().nunique()}")

Load in the df with the column "sale_date" as the date type. 

There are no nulls. So let us check for inconsistencies

In [6]:
sales_df = pd.read_csv(os.path.join(target_dir, 'sales.csv'), parse_dates=['sale_date'], date_format='%d-%m-%Y', dtype={'quantity': 'int32'})
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040200 entries, 0 to 1040199
Data columns (total 5 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   sale_id     1040200 non-null  str
 1   sale_date   1040200 non-null  datetime64[us]
 2   store_id    1040200 non-null  str
 3   product_id  1040200 non-null  str
 4   quantity    1040200 non-null  int32
dtypes: datetime64[us](1), int32(1), str(3)
memory usage: 35.7 MB

In [7]:
sales_df.duplicated().sum()

np.int64(0)

## ALL FIXED 
For the sales table, there are:
* No Nulls
* Date parsing handled
* No incosistent data sue to formatting
* No duplicates either

In [8]:
products_df = pd.read_csv(os.path.join(target_dir, 'products.csv'))
products_df.head()

  Product_ID         Product_Name Category_ID Launch_Date  Price
0        P-1              MacBook       CAT-1  2023-09-17   1149
1        P-2     MacBook Air (M1)       CAT-1  2023-11-11   1783
2        P-3     MacBook Air (M2)       CAT-1  2020-05-24   1588
3        P-4  MacBook Pro 13-inch       CAT-1  2021-01-17   1351
4        P-5  MacBook Pro 14-inch       CAT-1  2024-05-12    768

In [ ]:
products_df.info()

In [ ]:
products_df.describe(include='all')

In [9]:
products_df = pd.read_csv(os.path.join(target_dir, 'products.csv'), parse_dates=['Launch_Date'], date_format='%Y-%m-%d', dtype={'Price': 'int32'}) #'%d-%m-%Y'
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    89 non-null     str
 1   Product_Name  89 non-null     str
 2   Category_ID   89 non-null     str
 3   Launch_Date   89 non-null     datetime64[us]
 4   Price         89 non-null     int32
dtypes: datetime64[us](1), int32(1), str(3)
memory usage: 3.3 KB

In [10]:
products_df.duplicated().sum()

np.int64(0)

## ALL FIXED
For the products data:
* All claened too

In [11]:
stores_df = pd.read_csv(os.path.join(target_dir, 'stores.csv'))
stores_df.head()

  Store_ID             Store_Name           City        Country
0     ST-1     Apple Fifth Avenue       New York  United States
1     ST-2     Apple Union Square  San Francisco  United States
2     ST-3  Apple Michigan Avenue        Chicago  United States
3     ST-4        Apple The Grove    Los Angeles  United States
4     ST-5             Apple SoHo       New York  United States

In [12]:
stores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Store_ID    75 non-null     str
 1   Store_Name  75 non-null     str
 2   City        75 non-null     str
 3   Country     75 non-null     str
dtypes: str(4)
memory usage: 2.5 KB

In [13]:
stores_df.describe(include='all')

       Store_ID           Store_Name    City        Country
count        75                   75      75             75
unique       75                   69      47             19
top        ST-1  Apple Covent Garden  London  United States
freq          1                    2       4             15

In [14]:
print(f"Number of unique Store_ID values is : {stores_df['Store_ID'].nunique()}") 
print(f"Number of unique Store_Name values is : {stores_df['Store_Name'].nunique()}") 
print(f"Number of unique Country values is : {stores_df['Country'].nunique()}") 
print(f"Number of unique City values is : {stores_df['City'].nunique()}")

Number of unique Store_ID values is : 75
Number of unique Store_Name values is : 69
Number of unique Country values is : 19
Number of unique City values is : 47

In [15]:
# After capitalizing the IDs, we can check the number of unique IDs again to see if there are any duplicates due to case sensitivity.
print(f"Number of unique Store_ID values is : {stores_df['Store_ID'].str.upper().nunique()}") 
print(f"Number of unique Store_Name values is : {stores_df['Store_Name'].str.upper().nunique()}") 
print(f"Number of unique Country values is : {stores_df['Country'].str.upper().nunique()}") 
print(f"Number of unique City values is : {stores_df['City'].str.upper().nunique()}")

Number of unique Store_ID values is : 75
Number of unique Store_Name values is : 69
Number of unique Country values is : 19
Number of unique City values is : 47

In [16]:
stores_df = pd.read_json(os.path.join(target_dir, 'stores.json'))
stores_df.head()

  Store_ID             Store_Name           City        Country
0     ST-1     Apple Fifth Avenue       New York  United States
1     ST-2     Apple Union Square  San Francisco  United States
2     ST-3  Apple Michigan Avenue        Chicago  United States
3     ST-4        Apple The Grove    Los Angeles  United States
4     ST-5             Apple SoHo       New York  United States

In [17]:
stores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Store_ID    75 non-null     str
 1   Store_Name  75 non-null     str
 2   City        75 non-null     str
 3   Country     75 non-null     str
dtypes: str(4)
memory usage: 2.5 KB

In [18]:
stores_df.duplicated().sum()

np.int64(0)

In [19]:
warranty_df = pd.read_csv(os.path.join(target_dir, 'warranty.csv'), parse_dates=['claim_date'], date_format='%Y-%m-%d')
warranty_df.head()

   claim_id claim_date    sale_id repair_status
0  CL-58750 2024-01-30    YG-8782     Completed
1   CL-8874 2024-06-25  QX-999001       Pending
2  CL-14486 2024-08-13   JG-46890       Pending
3  CL-42187 2024-09-19    XJ-1731       Pending
4  CL-37590 2024-09-16   FG-95080     Completed

In [20]:
warranty_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   claim_id       30000 non-null  str
 1   claim_date     30000 non-null  datetime64[us]
 2   sale_id        30000 non-null  str
 3   repair_status  30000 non-null  str
dtypes: datetime64[us](1), str(3)
memory usage: 937.6 KB

In [21]:
warranty_df.describe(include='all')

        claim_id                  claim_date  sale_id repair_status
count      30000                       30000    30000         30000
unique     30000                         NaN    30000             4
top     CL-58750                         NaN  YG-8782   In Progress
freq           1                         NaN        1          7611
mean         NaN  2024-06-07 04:35:42.720000      NaN           NaN
min          NaN         2024-01-01 00:00:00      NaN           NaN
25%          NaN         2024-03-20 00:00:00      NaN           NaN
50%          NaN         2024-06-08 00:00:00      NaN           NaN
75%          NaN         2024-08-25 00:00:00      NaN           NaN
max          NaN         2024-11-12 00:00:00      NaN           NaN

In [22]:
warranty_df.duplicated().sum()

np.int64(0)

In [12]:
category_df = pd.read_csv(os.path.join(target_dir, 'category.csv'))
category_df.head()

  category_id category_name
0       CAT-1        Laptop
1       CAT-2         Audio
2       CAT-3        Tablet
3       CAT-4    Smartphone
4       CAT-5      Wearable

## Aggregations

In [29]:
products_df.columns = products_df.columns.str.lower()
stores_df.columns = stores_df.columns.str.lower()

In [30]:
# sales_df, products_df, warranty_df, stores_df
sales_df.head(2)

     sale_id  sale_date store_id product_id  quantity
0    YG-8782 2023-06-16    ST-10       P-38        10
1  QX-999001 2022-04-13    ST-63       P-48        10

In [31]:
products_df.head(2)

  product_id      product_name category_id launch_date  price
0        P-1           MacBook       CAT-1  2023-09-17   1149
1        P-2  MacBook Air (M1)       CAT-1  2023-11-11   1783

In [32]:
warranty_df.head(2)

   claim_id claim_date    sale_id repair_status
0  CL-58750 2024-01-30    YG-8782     Completed
1   CL-8874 2024-06-25  QX-999001       Pending

In [33]:
stores_df.head(2)

  store_id          store_name           city        country
0     ST-1  Apple Fifth Avenue       New York  United States
1     ST-2  Apple Union Square  San Francisco  United States

In [34]:
df = sales_df.merge(products_df, on='product_id', how='left')
df.head(2)

,sale_id,sale_date,store_id,product_id,quantity,product_name,category_id,launch_date,price
0,YG-8782,2023-06-16,ST-10,P-38,10,iPhone 13 Pro,CAT-4,2021-03-22,308
1,QX-999001,2022-04-13,ST-63,P-48,10,Apple Watch Nike Edition,CAT-5,2020-06-24,884

In [35]:
df = df.merge(warranty_df, on='sale_id', how='left')
df.head()

,sale_id,sale_date,store_id,product_id,quantity,product_name,category_id,launch_date,price,claim_id,claim_date,repair_status
0,YG-8782,2023-06-16,ST-10,P-38,10,iPhone 13 Pro,CAT-4,2021-03-22,308,CL-58750,2024-01-30,Completed
1,QX-999001,2022-04-13,ST-63,P-48,10,Apple Watch Nike Edition,CAT-5,2020-06-24,884,CL-8874,2024-06-25,Pending
2,JG-46890,2021-07-05,ST-26,P-79,5,Magic Trackpad,CAT-10,2024-05-25,1242,CL-14486,2024-08-13,Pending
3,XJ-1731,2022-07-20,ST-15,P-24,9,iPad mini (6th Generation),CAT-3,2022-11-27,573,CL-42187,2024-09-19,Pending
4,FG-95080,2022-03-18,ST-35,P-69,7,Apple TV+,CAT-8,2024-11-04,404,CL-37590,2024-09-16,Completed

In [36]:
df = df.merge(stores_df, on='store_id', how='left')
df.head(2)

,sale_id,sale_date,store_id,product_id,quantity,product_name,category_id,launch_date,price,claim_id,claim_date,repair_status,store_name,city,country
0,YG-8782,2023-06-16,ST-10,P-38,10,iPhone 13 Pro,CAT-4,2021-03-22,308,CL-58750,2024-01-30,Completed,Apple South Coast Plaza,Costa Mesa,United States
1,QX-999001,2022-04-13,ST-63,P-48,10,Apple Watch Nike Edition,CAT-5,2020-06-24,884,CL-8874,2024-06-25,Pending,Apple Parque La Colina,Bogota,Colombia

In [37]:
df.shape

(1040200, 15)

In [38]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040200 entries, 0 to 1040199
Data columns (total 15 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   sale_id        1040200 non-null  str
 1   sale_date      1040200 non-null  datetime64[us]
 2   store_id       1040200 non-null  str
 3   product_id     1040200 non-null  str
 4   quantity       1040200 non-null  int32
 5   product_name   1040200 non-null  str
 6   category_id    1040200 non-null  str
 7   launch_date    1040200 non-null  datetime64[us]
 8   price          1040200 non-null  int32
 9   claim_id       30000 non-null    str
 10  claim_date     30000 non-null    datetime64[us]
 11  repair_status  30000 non-null    str
 12  store_name     1040200 non-null  str
 13  city           1040200 non-null  str
 14  country        1040200 non-null  str
dtypes: datetime64[us](3), int32(2), str(10)
memory usage: 111.1 MB

In [40]:
# Some transformations
df['revenue'] = df['quantity'] * df['price']

In [42]:
# Revenue by Year
yearly_revenue = (
    df.groupby(df['sale_date'].dt.to_period('Y'))['revenue']
    .sum()
    .reset_index()
    .rename(columns={'sale_date': 'sale_month'})
)
yearly_revenue

  sale_month     revenue
0       2020  1269455486
1       2021  1264515755
2       2022  1269424007
3       2023  1261440123
4       2024  1101457659

In [43]:
# Revenue by Product Category
category_revenue = (
    df.groupby('category_id')
    .agg(
        total_revenue= ('revenue', 'sum'), 
        total_units_sold = ('quantity', 'sum'), 
        transaction_count = ('sale_id', 'count')
    )
    .sort_values(by = 'total_revenue', ascending=False)
    .reset_index()
)
category_revenue

  category_id  total_revenue  total_units_sold  transaction_count
0       CAT-3      953443623            645303             117142
1      CAT-10      927115953            899734             163849
2       CAT-4      865147932            834006             151636
3       CAT-2      794980579            707354             128731
4       CAT-1      763382551            640336             116369
5       CAT-5      667537447            582445             105521
6       CAT-7      538481345            642140             116812
7       CAT-8      368463489            447062              81561
8       CAT-6      191622603            192534              35014
9       CAT-9       96117508            130430              23565

In [44]:
# Top 3 Products by Volume
top_3_prods_by_vol = (
    df.groupby(['product_id', 'product_name'])
    .agg(total_units_sold= ('quantity', 'sum'))
    .sort_values(by = 'total_units_sold', ascending=False)
    .head(3)
    .reset_index()
)

top_3_prods_by_vol

  product_id          product_name  total_units_sold
0       P-51  Apple Watch Series 7             65739
1       P-74               HomePod             65623
2       P-45  Apple Watch Series 9             65481

In [45]:
top_3_prods_revenue = (
    df.groupby(['product_id', 'product_name'])
    .agg(total_revenue = ('revenue', 'sum'))
    .sort_values(by = 'total_revenue', ascending=False)
    .head(3)
    .reset_index()
)

top_3_prods_revenue

  product_id                product_name  total_revenue
0       P-68                 Apple Music      125453460
1       P-58                iMac 27-inch      124006372
2       P-25  iPad mini (5th Generation)      123951136

In [3]:
df = pd.read_parquet("../data/processed/cleaned_data.parquet")
df.head(2)

,sale_id,sale_date,store_id,product_id,quantity,product_name,category_id,launch_date,price,store_name,city,country,revenue
0,YG-8782,2023-06-16,ST-10,P-38,10,iPhone 13 Pro,CAT-4,2021-03-22,308,Apple South Coast Plaza,Costa Mesa,United States,3080
1,QX-999001,2022-04-13,ST-63,P-48,10,Apple Watch Nike Edition,CAT-5,2020-06-24,884,Apple Parque La Colina,Bogota,Colombia,8840

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040200 entries, 0 to 1040199
Data columns (total 13 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   sale_id       1040200 non-null  str
 1   sale_date     1040200 non-null  datetime64[us]
 2   store_id      1040200 non-null  str
 3   product_id    1040200 non-null  str
 4   quantity      1040200 non-null  Int32
 5   product_name  1040200 non-null  str
 6   category_id   1040200 non-null  str
 7   launch_date   1040200 non-null  datetime64[us]
 8   price         1040200 non-null  Int32
 9   store_name    1040200 non-null  str
 10  city          1040200 non-null  str
 11  country       1040200 non-null  str
 12  revenue       1040200 non-null  Int32
dtypes: Int32(3), datetime64[us](2), str(8)
memory usage: 165.4 MB