In [3]:
import pandas as pd
import os

## Script to download and Unzip Data from Kaggle

In [ ]:

from kaggle.api.kaggle_api_extended import KaggleApi

In [3]:
api = KaggleApi()
api.authenticate()

In [5]:
dataset_id = 'amangarg08/apple-retail-sales-dataset'
target_dir = '../data/raw'

In [7]:
os.makedirs(target_dir, exist_ok=True)

In [8]:
if os.listdir(target_dir):
    print(f"Data already exists in {target_dir}. Skipping download.")
else:
    print(f"Downloading dataset {dataset_id} to {target_dir}...")
    api.dataset_download_files(dataset_id, path=target_dir, unzip=True)
    print(f"Dataset {dataset_id} downloaded and extracted to {target_dir}.")

Downloading dataset amangarg08/apple-retail-sales-dataset to ../data/raw...
Dataset URL: https://www.kaggle.com/datasets/amangarg08/apple-retail-sales-dataset
Dataset amangarg08/apple-retail-sales-dataset downloaded and extracted to ../data/raw.

Files to use: **sales.csv**, **products.csv**, **stores.csv**, **warranty.csv**

In [6]:
sales_df = pd.read_csv(os.path.join(target_dir, 'sales.csv'))

In [7]:
sales_df.head()

     sale_id   sale_date store_id product_id  quantity
0    YG-8782  16-06-2023    ST-10       P-38        10
1  QX-999001  13-04-2022    ST-63       P-48        10
2   JG-46890  05-07-2021    ST-26       P-79         5
3    XJ-1731  20-07-2022    ST-15       P-24         9
4   FG-95080  18-03-2022    ST-35       P-69         7

In [11]:
sales_df.shape

(1040200, 5)

In [8]:
sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040200 entries, 0 to 1040199
Data columns (total 5 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   sale_id     1040200 non-null  str
 1   sale_date   1040200 non-null  str
 2   store_id    1040200 non-null  str
 3   product_id  1040200 non-null  str
 4   quantity    1040200 non-null  int64
dtypes: int64(1), str(4)
memory usage: 39.7 MB

In [10]:
sales_df.describe(include="all")

        sale_id   sale_date store_id product_id      quantity
count   1040200     1040200  1040200    1040200  1.040200e+06
unique  1040200        1778       75         89           NaN
top     YG-8782  10-08-2022    ST-30       P-60           NaN
freq          1         661    14113      11893           NaN
mean        NaN         NaN      NaN        NaN  5.500235e+00
std         NaN         NaN      NaN        NaN  2.874295e+00
min         NaN         NaN      NaN        NaN  1.000000e+00
25%         NaN         NaN      NaN        NaN  3.000000e+00
50%         NaN         NaN      NaN        NaN  5.000000e+00
75%         NaN         NaN      NaN        NaN  8.000000e+00
max         NaN         NaN      NaN        NaN  1.000000e+01

In [13]:
max(sales_df['quantity'])

10

In [16]:
print(f"Number of unique sale IDs: {sales_df['sale_id'].nunique()}")
print(f"Number of unique store IDs: {sales_df['store_id'].nunique()}")
print(f"Number of unique product IDs: {sales_df['product_id'].nunique()}")

Number of unique sale IDs: 1040200
Number of unique store IDs: 75
Number of unique product IDs: 89

In [19]:
# After capitalizing the IDs, we can check the number of unique IDs again to see if there are any duplicates due to case sensitivity.
print(f"Number of unique sale IDs: {sales_df['sale_id'].str.upper().nunique()}")
print(f"Number of unique store IDs: {sales_df['store_id'].str.upper().nunique()}")
print(f"Number of unique product IDs: {sales_df['product_id'].str.upper().nunique()}")

Number of unique sale IDs: 1040200
Number of unique store IDs: 75
Number of unique product IDs: 89

Load in the df with the column "sale_date" as the date type. 

There are no nulls. So let us check for inconsistencies

In [14]:
parsed_sales_df = pd.read_csv(os.path.join(target_dir, 'sales.csv'), parse_dates=['sale_date'], date_format='%d-%m-%Y', dtype={'quantity': 'int32'})
parsed_sales_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1040200 entries, 0 to 1040199
Data columns (total 5 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   sale_id     1040200 non-null  str
 1   sale_date   1040200 non-null  datetime64[us]
 2   store_id    1040200 non-null  str
 3   product_id  1040200 non-null  str
 4   quantity    1040200 non-null  int32
dtypes: datetime64[us](1), int32(1), str(3)
memory usage: 35.7 MB

## ALL FIXED 
For the sales table, there are:
* No Nulls
* Date parsing handled
* No incosistent data sue to formatting

In [15]:
products_df = pd.read_csv(os.path.join(target_dir, 'products.csv'))
products_df.head()

  Product_ID         Product_Name Category_ID Launch_Date  Price
0        P-1              MacBook       CAT-1  2023-09-17   1149
1        P-2     MacBook Air (M1)       CAT-1  2023-11-11   1783
2        P-3     MacBook Air (M2)       CAT-1  2020-05-24   1588
3        P-4  MacBook Pro 13-inch       CAT-1  2021-01-17   1351
4        P-5  MacBook Pro 14-inch       CAT-1  2024-05-12    768

In [16]:
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    89 non-null     str
 1   Product_Name  89 non-null     str
 2   Category_ID   89 non-null     str
 3   Launch_Date   89 non-null     str
 4   Price         89 non-null     int64
dtypes: int64(1), str(4)
memory usage: 3.6 KB

In [17]:
products_df.describe(include='all')

       Product_ID  Product_Name Category_ID Launch_Date        Price
count          89            89          89          89    89.000000
unique         89            88          10          88          NaN
top           P-1  HomePod mini      CAT-10  2023-11-10          NaN
freq            1             2          14           2          NaN
mean          NaN           NaN         NaN         NaN  1078.078652
std           NaN           NaN         NaN         NaN   501.628059
min           NaN           NaN         NaN         NaN   231.000000
25%           NaN           NaN         NaN         NaN   623.000000
50%           NaN           NaN         NaN         NaN  1149.000000
75%           NaN           NaN         NaN         NaN  1436.000000
max           NaN           NaN         NaN         NaN  1965.000000

In [18]:
products_df = pd.read_csv(os.path.join(target_dir, 'products.csv'), parse_dates=['Launch_Date'], date_format='%Y-%m-%d', dtype={'Price': 'int32'}) #'%d-%m-%Y'
products_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    89 non-null     str
 1   Product_Name  89 non-null     str
 2   Category_ID   89 non-null     str
 3   Launch_Date   89 non-null     datetime64[us]
 4   Price         89 non-null     int32
dtypes: datetime64[us](1), int32(1), str(3)
memory usage: 3.3 KB

## ALL FIXED
For the products data:
* All claened too

In [19]:
stores_df = pd.read_csv(os.path.join(target_dir, 'stores.csv'))
stores_df.head()

  Store_ID             Store_Name           City        Country
0     ST-1     Apple Fifth Avenue       New York  United States
1     ST-2     Apple Union Square  San Francisco  United States
2     ST-3  Apple Michigan Avenue        Chicago  United States
3     ST-4        Apple The Grove    Los Angeles  United States
4     ST-5             Apple SoHo       New York  United States

In [20]:
stores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Store_ID    75 non-null     str
 1   Store_Name  75 non-null     str
 2   City        75 non-null     str
 3   Country     75 non-null     str
dtypes: str(4)
memory usage: 2.5 KB

In [21]:
stores_df.describe(include='all')

       Store_ID           Store_Name    City        Country
count        75                   75      75             75
unique       75                   69      47             19
top        ST-1  Apple Covent Garden  London  United States
freq          1                    2       4             15

In [35]:
print(f"Number of unique Store_ID values is : {stores_df['Store_ID'].nunique()}") 
print(f"Number of unique Store_Name values is : {stores_df['Store_Name'].nunique()}") 
print(f"Number of unique Country values is : {stores_df['Country'].nunique()}") 
print(f"Number of unique City values is : {stores_df['City'].nunique()}")

Number of unique Store_ID values is : 75
Number of unique Store_Name values is : 69
Number of unique Country values is : 19
Number of unique City values is : 47

In [38]:
# After capitalizing the IDs, we can check the number of unique IDs again to see if there are any duplicates due to case sensitivity.
print(f"Number of unique Store_ID values is : {stores_df['Store_ID'].str.upper().nunique()}") 
print(f"Number of unique Store_Name values is : {stores_df['Store_Name'].str.upper().nunique()}") 
print(f"Number of unique Country values is : {stores_df['Country'].str.upper().nunique()}") 
print(f"Number of unique City values is : {stores_df['City'].str.upper().nunique()}")

Number of unique Store_ID values is : 75
Number of unique Store_Name values is : 69
Number of unique Country values is : 19
Number of unique City values is : 47

In [26]:
stores_df = pd.read_json(os.path.join(target_dir, 'stores.json'))
stores_df.head()

  Store_ID             Store_Name           City        Country
0     ST-1     Apple Fifth Avenue       New York  United States
1     ST-2     Apple Union Square  San Francisco  United States
2     ST-3  Apple Michigan Avenue        Chicago  United States
3     ST-4        Apple The Grove    Los Angeles  United States
4     ST-5             Apple SoHo       New York  United States

In [27]:
stores_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Store_ID    75 non-null     str
 1   Store_Name  75 non-null     str
 2   City        75 non-null     str
 3   Country     75 non-null     str
dtypes: str(4)
memory usage: 2.5 KB

In [22]:
warranty_df = pd.read_csv(os.path.join(target_dir, 'warranty.csv'), parse_dates=['claim_date'], date_format='%Y-%m-%d')
warranty_df.head()

   claim_id claim_date    sale_id repair_status
0  CL-58750 2024-01-30    YG-8782     Completed
1   CL-8874 2024-06-25  QX-999001       Pending
2  CL-14486 2024-08-13   JG-46890       Pending
3  CL-42187 2024-09-19    XJ-1731       Pending
4  CL-37590 2024-09-16   FG-95080     Completed

In [23]:
warranty_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   claim_id       30000 non-null  str
 1   claim_date     30000 non-null  datetime64[us]
 2   sale_id        30000 non-null  str
 3   repair_status  30000 non-null  str
dtypes: datetime64[us](1), str(3)
memory usage: 937.6 KB

In [24]:
warranty_df.describe(include='all')

        claim_id                  claim_date  sale_id repair_status
count      30000                       30000    30000         30000
unique     30000                         NaN    30000             4
top     CL-58750                         NaN  YG-8782   In Progress
freq           1                         NaN        1          7611
mean         NaN  2024-06-07 04:35:42.720000      NaN           NaN
min          NaN         2024-01-01 00:00:00      NaN           NaN
25%          NaN         2024-03-20 00:00:00      NaN           NaN
50%          NaN         2024-06-08 00:00:00      NaN           NaN
75%          NaN         2024-08-25 00:00:00      NaN           NaN
max          NaN         2024-11-12 00:00:00      NaN           NaN